# Generated by Django 3.2.7 on 2021-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general_query', 'General Query'), ('delivery_query', 'Delivery Query'), ('return_query', 'Return Query'), ('blog_contribution', 'Blog Contribution'), ('complaint', 'Complaint')], default='general_query', max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
