# Generated by Django 3.2.7 on 2021-11-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='subscription_email',
        ),
    ]
