# Generated by Django 3.2.7 on 2021-10-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='info',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
